version: '3'

services:
  app:
    build: .
    ports:
      - "8080:80"

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data-preprod:/var/lib/mysql
      # Initialize database with the provided sql script.
      - ./sql/import.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

volumes:
  mariadb-data-preprod: