version: "3"
name: videgrenier-prod

services:
  app:
    image: ghcr.io/yamadablog/docker-project:master
    ports:
      - "8080:80"
    volumes:
      - upload-data-prod:/var/www/html/public/storage

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data-prod:/var/lib/mysql
      # Initialize database with the provided sql script.
      - ./sql/import.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

volumes:
  upload-data-prod:
  mariadb-data-prod:
