version: "3"
name: videgrenier-dev

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - .devcontainer/000-default.conf:/etc/apache2/sites-enabled/000-default.conf

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
      # Initialize database with the provided sql script.
      - ./sql/import.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./:/app

volumes:
  mariadb-data: